# Generated by Django 4.1.7 on 2023-03-16 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("CHAR", "- SHORT TEXT (Titles, Names etc)"),
                            ("TEXT", "- LARGE TEXT (Rich Text Editor)"),
                            ("INTEGER", "- INTEGER"),
                            ("FLOAT", "- DECIMAL (i.e., Amount (g) = 23.72)"),
                            ("BOOLEAN", "- CHECKBOX (True / False)"),
                        ],
                        max_length=8,
                    ),
                ),
                ("order", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.field"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="BooleanForm",
            fields=[
                (
                    "form_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.form",
                    ),
                ),
                (
                    "type",
                    models.CharField(default="bool", editable=False, max_length=4),
                ),
                ("value", models.BooleanField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.form",),
        ),
        migrations.CreateModel(
            name="CharacterForm",
            fields=[
                (
                    "form_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.form",
                    ),
                ),
                (
                    "type",
                    models.CharField(default="char", editable=False, max_length=4),
                ),
                ("value", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.form",),
        ),
        migrations.CreateModel(
            name="FloatForm",
            fields=[
                (
                    "form_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.form",
                    ),
                ),
                (
                    "type",
                    models.CharField(default="float", editable=False, max_length=5),
                ),
                ("value", models.FloatField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.form",),
        ),
        migrations.CreateModel(
            name="IntegerForm",
            fields=[
                (
                    "form_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.form",
                    ),
                ),
                ("type", models.CharField(default="int", editable=False, max_length=3)),
                ("value", models.IntegerField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.form",),
        ),
        migrations.CreateModel(
            name="TextForm",
            fields=[
                (
                    "form_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.form",
                    ),
                ),
                (
                    "type",
                    models.CharField(default="text", editable=False, max_length=4),
                ),
                ("value", models.CharField(max_length=2048)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.form",),
        ),
        migrations.CreateModel(
            name="Object",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_counter", models.IntegerField(default=0, editable=False)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.service"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="form",
            name="object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.object"
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.object"
            ),
        ),
    ]
