# Generated by Django 4.1.7 on 2023-03-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textform",
            name="value",
            field=models.TextField(),
        ),
    ]
