# Generated by Django 4.1.7 on 2023-03-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_textform_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterform",
            name="value",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="textform",
            name="value",
            field=models.TextField(default=""),
        ),
    ]
