# Generated by Django 4.1.7 on 2023-03-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_characterform_value_alter_textform_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textform",
            name="value",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
