# Generated by Django 4.1.7 on 2023-03-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_textform_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booleanform",
            name="value",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="characterform",
            name="value",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="floatform",
            name="value",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="integerform",
            name="value",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
