# Generated by Django 4.1.7 on 2023-04-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_booleanform_value_alter_characterform_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="form_type",
            field=models.CharField(
                choices=[
                    ("CHAR", "SHORT TEXT (Titles, Names etc)"),
                    ("TEXT", "LARGE TEXT (Rich Text Editor)"),
                    ("INTEGER", "INTEGER"),
                    ("FLOAT", "DECIMAL (i.e., Amount (g) = 23.72)"),
                    ("BOOLEAN", "CHECKBOX (True / False)"),
                ],
                max_length=8,
            ),
        ),
    ]
