# Generated by Django 4.1.7 on 2023-11-03 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_field_form_type_alter_field_object"),
    ]

    operations = [
        migrations.RenameField(
            model_name="field",
            old_name="object",
            new_name="service",
        ),
    ]
